version: "3.8"
services:
  nsp_backend:
    container_name: nsp_backend
    # entrypoint: ["/bin/bash", "./entrypoint.sh"]
    image: hossamyahia107/export-to-google:0.0.2
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - EXTERNAL_PORT=3000
      - PGUSER=francesco
      - PGPASSWORD=12345
      - PGDATABASE=nps_database
      - PGHOST=nsp_db # NAME OF THE SERVICE
      - PGPORT=5432
    volumes: 
      - .:/app
      - /app/node_modules
    depends_on:
      - nsp_db
  nsp_db:
    container_name: nsp_db
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=francesco
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=nps_database
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}
